### ISSUE TITLE
Update to newest version

### ISSUE THREAD

**Issue by YT-Advanced** [PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.2#1]
Hello, I very love your repos but can you update this cursor to latest version that support big cursor. Thanks

**Comment by PSGitHubUser1** [comment]
Oh. I up

**Comment by PSGitHubUser1** [comment]
Done! Added new release with `big v2` folder

**Comment by PSGitHubUser1** [comment]
This issue has been closed as completed.
