### ISSUE TITLE
Update to new version which has newer colors

### ISSUE THREAD

**Issue by Lolicchi** [PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.2#2]
Hlo, ty for this, there is a new update now with two new colors indigo and amber, and i think they made it more HD now. ty again <33.

https://www.deviantart.com/jepricreations/art/Windows-11-Cursors-Concept-HD-v2-890672103
![image](https://user-images.githubusercontent.com/67526745/199148162-357aee1b-2d20-4b6d-a0c2-ea4bbac63b44.png)

**Comment by PSGitHubUser1** [comment]
Ok ok.

**Comment by PSGitHubUser1** [comment]
Completed!

**Comment by PSGitHubUser1** [comment]
This issue has been closed as completed.
